name: CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint (ruff)
        run: ruff check .

      - name: Unit tests
        run: pytest -q

      - name: Quick training smoke (v0.1)
        env:
          MODEL_VERSION: "0.1.0"
        run: |
          python -m src.train
          ls -la artifacts
          cat artifacts/metrics.json

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-and-metrics
          path: artifacts/**

