name: 2 - Release, Deploy, and Publish Docker Image

on:
  push:
    tags:
      - 'v*'   # e.g., v0.1.0, v0.2.0

env:
  REGISTRY: ghcr.io

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Train model for this tag
        env:
          MODEL_VERSION: "${{ github.ref_name }}"
        run: |
          python -m src.train
          test -f artifacts/model.joblib
          test -f artifacts/metrics.json
          echo "Artifacts ready."

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ✅ Compute lowercase image as a **step output** (usable in `with:`)
      - name: Compute lowercase image tag
        id: img
        run: |
          lower_repo="$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')"
          echo "image=${{ env.REGISTRY }}/${lower_repo}:${{ github.ref_name }}" >> "$GITHUB_OUTPUT"
          echo "IMAGE=${{ env.REGISTRY }}/${lower_repo}:${{ github.ref_name }}"
      
      - name: Build Docker Image (bakes artifacts)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ steps.img.outputs.image }}

      - name: Smoke test container
        env:
          IMAGE: ${{ steps.img.outputs.image }}   # make it available to the shell
        run: |
          docker run -d -p 8000:8000 --name smoke "$IMAGE"
          sleep 5
          curl -fsS http://localhost:8000/health
          curl -fsS -X POST http://localhost:8000/predict \
            -H "Content-Type: application/json" \
            -d '{"age":0.02,"sex":-0.044,"bmi":0.06,"bp":-0.03,"s1":-0.02,"s2":0.03,"s3":-0.02,"s4":0.02,"s5":0.02,"s6":-0.001}'
          docker rm -f smoke

      - name: Push image to GHCR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.img.outputs.image }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: artifacts/metrics.json
          body: |
            Release ${{ github.ref_name }}
            - Image: ${{ steps.img.outputs.image }}
            - Metrics attached (metrics.json).
            - See CHANGELOG.md for details.
